// C++ code
//
void setup()
{
  pinMode(1, OUTPUT);
  pinMode(8, OUTPUT);
  pinMode(9, OUTPUT);
  pinMode(A2, OUTPUT);
  pinMode(2, OUTPUT);
  pinMode(7, OUTPUT);
  pinMode(10, OUTPUT);
  pinMode(A1, OUTPUT);
  pinMode(3, OUTPUT);
  pinMode(6, OUTPUT);
  pinMode(11, OUTPUT);
  pinMode(A0, OUTPUT);
  pinMode(4, OUTPUT);
  pinMode(5, OUTPUT);
  pinMode(12, OUTPUT);
  pinMode(13, OUTPUT);
}

void loop()
{
  digitalWrite(1, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(A2, HIGH);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(2, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(10, HIGH);
  digitalWrite(A1, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(3, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(A0, HIGH);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(4, HIGH);
  digitalWrite(5, HIGH);
  digitalWrite(1, LOW);
  digitalWrite(8, LOW);
  digitalWrite(9, LOW);
  digitalWrite(A2, LOW);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(2, LOW);
  digitalWrite(7, LOW);
  digitalWrite(10, LOW);
  digitalWrite(A1, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(3, LOW);
  digitalWrite(6, LOW);
  digitalWrite(11, LOW);
  digitalWrite(A0, LOW);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(4, LOW);
  digitalWrite(5, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(1, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(A2, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(2, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(10, HIGH);
  digitalWrite(A1, HIGH);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(3, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(A0, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(4, HIGH);
  digitalWrite(5, HIGH);
  digitalWrite(1, LOW);
  digitalWrite(8, LOW);
  digitalWrite(9, LOW);
  digitalWrite(A2, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(2, LOW);
  digitalWrite(7, LOW);
  digitalWrite(10, LOW);
  digitalWrite(A1, LOW);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(3, LOW);
  digitalWrite(6, LOW);
  digitalWrite(11, LOW);
  digitalWrite(A0, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(4, LOW);
  digitalWrite(5, LOW);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(1, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(A2, HIGH);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(2, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(10, HIGH);
  digitalWrite(A1, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(3, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(A0, HIGH);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(4, HIGH);
  digitalWrite(5, HIGH);
  digitalWrite(1, LOW);
  digitalWrite(8, LOW);
  digitalWrite(9, LOW);
  digitalWrite(A2, LOW);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(2, LOW);
  digitalWrite(7, LOW);
  digitalWrite(10, LOW);
  digitalWrite(A1, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(3, LOW);
  digitalWrite(6, LOW);
  digitalWrite(11, LOW);
  digitalWrite(A0, LOW);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(4, LOW);
  digitalWrite(5, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(1, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(A2, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(2, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(10, HIGH);
  digitalWrite(A1, HIGH);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(3, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(A0, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(4, HIGH);
  digitalWrite(5, HIGH);
  digitalWrite(1, LOW);
  digitalWrite(8, LOW);
  digitalWrite(9, LOW);
  digitalWrite(A2, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(2, LOW);
  digitalWrite(7, LOW);
  digitalWrite(10, LOW);
  digitalWrite(A1, LOW);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(3, LOW);
  digitalWrite(6, LOW);
  digitalWrite(11, LOW);
  digitalWrite(A0, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(4, LOW);
  digitalWrite(5, LOW);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(1, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(A2, HIGH);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(2, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(10, HIGH);
  digitalWrite(A1, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(3, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(A0, HIGH);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(4, HIGH);
  digitalWrite(5, HIGH);
  digitalWrite(1, LOW);
  digitalWrite(8, LOW);
  digitalWrite(9, LOW);
  digitalWrite(A2, LOW);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(2, LOW);
  digitalWrite(7, LOW);
  digitalWrite(10, LOW);
  digitalWrite(A1, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(3, LOW);
  digitalWrite(6, LOW);
  digitalWrite(11, LOW);
  digitalWrite(A0, LOW);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(4, LOW);
  digitalWrite(5, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(75); // Wait for 75 millisecond(s)
  digitalWrite(1, HIGH);
  digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  digitalWrite(A0, HIGH);
  digitalWrite(A1, HIGH);
  digitalWrite(A2, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(400);
  digitalWrite(1, LOW);
  digitalWrite(2, LOW);
  digitalWrite(3, LOW);
  digitalWrite(4, LOW);
  digitalWrite(A0, LOW);
  digitalWrite(A1, LOW);
  digitalWrite(A2, LOW);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(10, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(400);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  digitalWrite(7, LOW);
  digitalWrite(8, LOW);
  digitalWrite(9, LOW);
  digitalWrite(10, LOW);
  digitalWrite(11, LOW);
  digitalWrite(1, HIGH);
  digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  digitalWrite(A0, HIGH);
  digitalWrite(A1, HIGH);
  digitalWrite(A2, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(400);
  digitalWrite(1, LOW);
  digitalWrite(2, LOW);
  digitalWrite(3, LOW);
  digitalWrite(4, LOW);
  digitalWrite(A0, LOW);
  digitalWrite(A1, LOW);
  digitalWrite(A2, LOW);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(10, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(400);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  digitalWrite(7, LOW);
  digitalWrite(8, LOW);
  digitalWrite(9, LOW);
  digitalWrite(10, LOW);
  digitalWrite(11, LOW);
  digitalWrite(1, HIGH);
  digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  digitalWrite(A0, HIGH);
  digitalWrite(A1, HIGH);
  digitalWrite(A2, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(400);
  digitalWrite(1, LOW);
  digitalWrite(2, LOW);
  digitalWrite(3, LOW);
  digitalWrite(4, LOW);
  digitalWrite(A0, LOW);
  digitalWrite(A1, LOW);
  digitalWrite(A2, LOW);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(10, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  digitalWrite(7, LOW);
  digitalWrite(8, LOW);
  digitalWrite(11, LOW);
  digitalWrite(10, LOW);
  digitalWrite(9, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(125);
  digitalWrite(1, HIGH);
  digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  digitalWrite(A0, HIGH);
  digitalWrite(A1, HIGH);
  digitalWrite(A2, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(125);
  digitalWrite(1, LOW);
  digitalWrite(2, LOW);
  digitalWrite(3, LOW);
  digitalWrite(4, LOW);
  digitalWrite(A0, LOW);
  digitalWrite(A1, LOW);
  digitalWrite(A2, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(125);
  digitalWrite(1, HIGH);
  digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  digitalWrite(A0, HIGH);
  digitalWrite(A1, HIGH);
  digitalWrite(A2, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(125);
  digitalWrite(1, LOW);
  digitalWrite(2, LOW);
  digitalWrite(3, LOW);
  digitalWrite(4, LOW);
  digitalWrite(A0, LOW);
  digitalWrite(A1, LOW);
  digitalWrite(A2, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(125);
  digitalWrite(1, HIGH);
  digitalWrite(2, HIGH);
  digitalWrite(3, HIGH);
  digitalWrite(4, HIGH);
  digitalWrite(A0, HIGH);
  digitalWrite(A1, HIGH);
  digitalWrite(A2, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(125);
  digitalWrite(1, LOW);
  digitalWrite(2, LOW);
  digitalWrite(3, LOW);
  digitalWrite(4, LOW);
  digitalWrite(A0, LOW);
  digitalWrite(A1, LOW);
  digitalWrite(A2, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(125);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(10, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(125);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  digitalWrite(7, LOW);
  digitalWrite(8, LOW);
  digitalWrite(11, LOW);
  digitalWrite(10, LOW);
  digitalWrite(9, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(125);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(10, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(125);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  digitalWrite(7, LOW);
  digitalWrite(8, LOW);
  digitalWrite(11, LOW);
  digitalWrite(10, LOW);
  digitalWrite(9, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(125);
  digitalWrite(5, HIGH);
  digitalWrite(6, HIGH);
  digitalWrite(7, HIGH);
  digitalWrite(8, HIGH);
  digitalWrite(11, HIGH);
  digitalWrite(10, HIGH);
  digitalWrite(9, HIGH);
  digitalWrite(12, LOW);
  digitalWrite(13, HIGH);
  delay(125);
  digitalWrite(5, LOW);
  digitalWrite(6, LOW);
  digitalWrite(7, LOW);
  digitalWrite(8, LOW);
  digitalWrite(11, LOW);
  digitalWrite(10, LOW);
  digitalWrite(9, LOW);
  digitalWrite(12, HIGH);
  digitalWrite(13, LOW);
  delay(125);
}