name: Build and Deploy Vite Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build the Project
        run: npm run build

      # Create a .nojekyll file to disable Jekyll processing on GitHub Pages
      - name: Create .nojekyll File
        run: touch docs/.nojekyll

      - name: Commit and Push Build
        run: |
          git config user.name "qwertyhnbvdtyhcfgyu"
          git config user.email "ttdtdtd035@gmail.com"
          git add docs
          git pull
          git commit -m "Deploy built site [skip ci]" || echo "No changes to commit"
          git push